[package]
name = "wlan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ifstructs = "0.1.1"
pnet_datalink = "0.33.0"

[build-dependencies]
bindgen = "0.63.0"
cc = "1.0.78"
