[package]
name = "aux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wlan = {path="../wlan"}
pnet_datalink ="0.33.0"
libwifi = "0.3"
nix ={version="0.26",feature="ioctl"}